# Generated by Django 2.1.7 on 2019-03-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190322_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colors',
            new_name='colours',
        ),
    ]
